Revert "Fix unused{,-but-set}-variable compiler warnings."
This reverts commit 6c6e695878714b2ec8bd4f8aeb52f2946f6e6efc.

The commit introduced the following compiler error:

[100/255] Compiling posix/JackNetUnixSocket.cpp
../posix/JackNetUnixSocket.cpp: In member function 'int Jack::JackNetUnixSocket::NewSocket()':
../posix/JackNetUnixSocket.cpp:126:32: error: 'tos' was not declared in this scope
         socklen_t len = sizeof(tos);